In [56]:
from nptyping import NDArray, Shape,  UInt64
from typing import Any
import numpy as np

data : NDArray[Shape["10"], Any] = np.arange(1,11)

print(data)

[ 1  2  3  4  5  6  7  8  9 10]


https://pandera.readthedocs.io/en/stable/index.html

In [1]:
%pip install pandera

Note: you may need to restart the kernel to use updated packages.


In [16]:
import pandas as pd
import pandera as pa

# data table in excel is call Dataframe in Pandas
# SERIES TYPE - 1 Row and 1 Column extracted is called Series, 
# DATA FRAME TYPE - 2 or more than 2 series are combined togather makes DataFrame



In [11]:
l1 : list[int] = [1,2,3,4,5,6,7,8,9]
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
s1 : pd.Series = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
s1 : pd.Series = pd.Series((1,2,3,4,5))
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [14]:
s1 : pd.Series = pd.Series({"a" : 10,
                            "b" : 20,
                            "c" : 30,
                            "d" : 40,
                            "e" : 50,
                            "f" : 60,
                            "g" : 70})
s1  

a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64

In [22]:
values : list[int] = [1,2,3,4,5]
index1 : list[str] = ['a','b','c','d','e']

s1 : pd.Series = pd.Series(values, index=index1) 
s1


a    1
b    2
c    3
d    4
e    5
dtype: int64

In [24]:
values : list[int] = [1,2,3,4,5]
index1 : list[list[str]] = [['a1','a1','a1','b1','b1'],
                            ['a','b','c','d','e']]

s1 : pd.Series = pd.Series(values, index=index1) 
s1



a1  a    1
    b    2
    c    3
b1  d    4
    e    5
dtype: int64

In [29]:
import numpy as np
values : list[int] = [1,2,3,4,5]
index1 : list[list[str]] = [['a1','a1','a1','b1','b1'],
                            ['a','b','c','d','e']]

s1 : pd.Series = pd.Series(values, index=index1, name = "Student_Data",dtype = np.int32) 
s1


a1  a    1
    b    2
    c    3
b1  d    4
    e    5
Name: Student_Data, dtype: int32

In [25]:
from nptyping import DataFrame, Structure as S
#from beartype import beartype



In [3]:
import pandas as pd
import pandera as pa

# data to validate
df = pd.DataFrame({
    "column1": [1, 4, 0, 10, 9],
    "column2": [-1.3, -1.4, -2.9, -10.1, -20.4],
    "column3": ["value_1", "value_2", "value_3", "value_2", "value_1"],
})

# define schema
schema = pa.DataFrameSchema({
    "column1": pa.Column(int, checks=pa.Check.le(10)),
    "column2": pa.Column(float, checks=pa.Check.lt(-1.2)),
    "column3": pa.Column(str, checks=[
        pa.Check.str_startswith("value_"),
        # define custom checks as functions that take a series as input and
        # outputs a boolean or boolean Series
        pa.Check(lambda s: s.str.split("_", expand=True).shape[1] == 2)
    ]),
})

validated_df = schema(df)
print(validated_df)

   column1  column2  column3
0        1     -1.3  value_1
1        4     -1.4  value_2
2        0     -2.9  value_3
3       10    -10.1  value_2
4        9    -20.4  value_1


## DataFrame

In [7]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="Student id")
s2 : pd.Series = pd.Series([10,20,30,40,50], name = "Score")
s3 : pd.Series = pd.Series(["Hamza","Ali","Junaid","Rashid","Konain"], name = "Student name")

df1 : pd.DataFrame = pd.DataFrame({"Student id" : s1, "Score" : s2, "Student name" : s3})

df1

Student id  Score Student name
0           1     10        Hamza
1           2     20          Ali
2           3     30       Junaid
3           4     40       Rashid
4           5     50       Konain

In [13]:
s1 : pd.Series = pd.Series([1,2,3,4,5])
s2 : pd.Series = pd.Series([10,20,30,40,50])
s3 : pd.Series = pd.Series(["Hamza","Ali","Junaid","Rashid","Konain"])

df1 : pd.DataFrame = pd.DataFrame({"Student id" : s1, "Score" : s2, "Student name" : s3})

df1

Student id  Score Student name
0           1     10        Hamza
1           2     20          Ali
2           3     30       Junaid
3           4     40       Rashid
4           5     50       Konain

In [12]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="Student id")
s2 : pd.Series = pd.Series([10,20,30,40,50], name = "Score")
s3 : pd.Series = pd.Series(["Hamza","Ali","Junaid","Rashid","Konain"], name = "Student name")

df1 : pd.DataFrame = pd.DataFrame([s1,s2,s3])

df1  # COLUMN NAMES BECAME ROW NAMES SO BE CAREFUL 

0    1       2       3       4
Student id        1    2       3       4       5
Score            10   20      30      40      50
Student name  Hamza  Ali  Junaid  Rashid  Konain

In [10]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="Student id")
s2 : pd.Series = pd.Series([10,20,30,40,50], name = "Score")
s3 : pd.Series = pd.Series(["Hamza","Ali","Junaid","Rashid","Konain"], name = "Student name")

df1 : pd.DataFrame = pd.concat([s1,s2,s3],axis=1)
df1

Student id  Score Student name
0           1     10        Hamza
1           2     20          Ali
2           3     30       Junaid
3           4     40       Rashid
4           5     50       Konain

In [24]:
data : list[list[int]] = [[1,2,3],[4,5,6],[7,8,9]]

df1 : pd.DataFrame = pd.DataFrame(data, columns =["A","B","C"], index=["x","y","z"])

df1

A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [29]:
df1.columns


Index(['A', 'B', 'C'], dtype='object')

In [31]:
df1.index

Index(['x', 'y', 'z'], dtype='object')

In [32]:
df1.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [1]:
from nptyping import NDArray, Shape,  UInt64
from typing import Any
import numpy as np

data : NDArray[Shape["10,10"], Any] = np.arange(10*10).reshape(10,10)
data


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
import pandas as pd
import pandera as pa

data : NDArray[Shape["10,10"], Any] = np.arange(10*10).reshape(10,10)

df : pd.DataFrame = pd.DataFrame(data, columns=list("ABCDEFGHIJ"))
df

A   B   C   D   E   F   G   H   I   J
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [21]:
import pandas as pd
import pandera as pa

dflist : list[pd.DataFrame] = pd.read_html("https://www.w3schools.com/python/python_operators.asp")
dflist

[  Operator            Name Example    Try it
 0        +        Addition   x + y  Try it »
 1        -     Subtraction   x - y  Try it »
 2        *  Multiplication   x * y  Try it »
 3        /        Division   x / y  Try it »
 4        %         Modulus   x % y  Try it »
 5       **  Exponentiation  x ** y  Try it »
 6       //  Floor division  x // y  Try it »,
    Operator  Example     Same As    Try it
 0         =    x = 5       x = 5  Try it »
 1        +=   x += 3   x = x + 3  Try it »
 2        -=   x -= 3   x = x - 3  Try it »
 3        *=   x *= 3   x = x * 3  Try it »
 4        /=   x /= 3   x = x / 3  Try it »
 5        %=   x %= 3   x = x % 3  Try it »
 6       //=  x //= 3  x = x // 3  Try it »
 7       **=  x **= 3  x = x ** 3  Try it »
 8        &=   x &= 3   x = x & 3  Try it »
 9        |=   x |= 3   x = x | 3  Try it »
 10       ^=   x ^= 3   x = x ^ 3  Try it »
 11      >>=  x >>= 3  x = x >> 3  Try it »
 12      <<=  x <<= 3  x = x << 3  Try it »,
   Operator   

In [22]:
dflist[0]

Operator            Name Example    Try it
0        +        Addition   x + y  Try it »
1        -     Subtraction   x - y  Try it »
2        *  Multiplication   x * y  Try it »
3        /        Division   x / y  Try it »
4        %         Modulus   x % y  Try it »
5       **  Exponentiation  x ** y  Try it »
6       //  Floor division  x // y  Try it »

In [23]:
df : pd.DataFrame = pd.read_json("https://www.w3schools.com/python/pandas/data.js")

df

Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [25]:
import pandas as pd
import pandera as pa

# data to validate
df = pd.DataFrame({
    "column1": [1, 4, 0, 10, 9],
    "column2": [-1.3, -1.4, -2.9, -10.1, -20.4],
    "column3": ["value_1", "value_2", "value_3", "value_2", "value_1"],
})

# define schema
schema = pa.DataFrameSchema({
    "column1": pa.Column(int, checks=pa.Check.le(10)),
    "column2": pa.Column(float, checks=pa.Check.lt(-1.2)),
    "column3": pa.Column(str, checks=[
        pa.Check.str_startswith("value_"),
        # define custom checks as functions that take a series as input and
        # outputs a boolean or boolean Series
        pa.Check(lambda s: s.str.split("_", expand=True).shape[1] == 2)
    ]),
})

validated_df = schema(df)
print(validated_df)

   column1  column2  column3
0        1     -1.3  value_1
1        4     -1.4  value_2
2        0     -2.9  value_3
3       10    -10.1  value_2
4        9    -20.4  value_1


In [26]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'list[HashableT] | Callable[[Hashable], bool] | None' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Sequence[str] | Mapping[str, Sequence[str]] | None' = None,
    keep_default_na: 'bool' = True,
    n

In [28]:
dir(pa.Check)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_check_fn_code',
 'between',
 'eq',
 'equal_to',
 'equal_to',
 'from_builtin_check_name',
 'ge',
 'get_backend',
 'get_builtin_check_fn',
 'greater_than',
 'greater_than',
 'greater_than_or_equal_to',
 'greater_than_or_equal_to',
 'gt',
 'in_range',
 'in_range',
 'isin',
 'isin',
 'le',
 'less_than',
 'less_than',
 'less_than_or_equal_to',
 'less_than_or_equal_to',
 'lt',
 'ne',
 'not_equal_to',
 'not_equal_to',
 'notin',
 'notin',
 'one_sample_ttest',
 'register_backend',
 'register_builtin_check_fn',
 'str_contains',
 'str_contains',
 'str_endswith',
 'str_endswith',


# Slicing and Indexing

* series_variable[index]
* dataFrame
    * loc
    * iloc
    * at
    * iat


In [38]:
s1 : pd.Series = pd.Series([1,2,3,4,5])
display(s1)

print("Apply Slicing")

display(s1[1]) 

display(s1[1:4]) # Slicing till 4 will not include the last index

0    1
1    2
2    3
3    4
4    5
dtype: int64

Apply Slicing


2

1    2
2    3
3    4
dtype: int64

In [41]:
s1 : pd.Series = pd.Series([1,2,3,4,5])
display(s1)

print("Apply Slicing")

display(s1.iloc[1:4])  # iloc = index location (numbers) same as numpy slicing, last index excluded

0    1
1    2
2    3
3    4
4    5
dtype: int64

Apply Slicing


1    2
2    3
3    4
dtype: int64

In [43]:
s1 : pd.Series = pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
display(s1)

print("Apply Slicing")

display(s1.loc["a" : "d"]) # Index location (label) which includes end index too

a    1
b    2
c    3
d    4
e    5
dtype: int64

Apply Slicing


a    1
b    2
c    3
d    4
dtype: int64

In [47]:
s1 : pd.Series = pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
display(s1)

print("Apply Slicing")

display(s1.iat[1]) # Index location (number) extract one cell value and can be updated

a    1
b    2
c    3
d    4
e    5
dtype: int64

Apply Slicing


2

In [46]:
s1 : pd.Series = pd.Series([1,2,3,4,5], index = ['a', 'b', 'c', 'd', 'e'])
display(s1)

print("Apply Slicing")

display(s1.at["d"]) # Index location (label) extract one cell value and can be updated

a    1
b    2
c    3
d    4
e    5
dtype: int64

Apply Slicing


4

In [1]:
import pandas as pd
import pandera as pa

x : str = """

21:42:29 From Ahmed to Everyone:
    PIAIC110905

23:42:31 From Aslam to Everyone:
    PIAIC310906

23:42:31 From Ali to Everyone:
    PIAIC310907

23:42:31 From Ahad to Everyone:
    PIAIC310908

"""

import re

patterns : str = r'''
(\d{2}:\d{2}:\d{2}) From (.*) to Everyone:
    (PIAIC-? ?\d{5,6})
'''




data : list[list[str]] = re.findall(patterns, x)

data

[('21:42:29', 'Ahmed', 'PIAIC110905'),
 ('23:42:31', 'Aslam', 'PIAIC310906'),
 ('23:42:31', 'Ali', 'PIAIC310907'),
 ('23:42:31', 'Ahad', 'PIAIC310908')]

In [2]:
df : pd.DataFrame = pd.DataFrame(data,columns=['Time','Name','Roll Number'])

df

Time   Name  Roll Number
0  21:42:29  Ahmed  PIAIC110905
1  23:42:31  Aslam  PIAIC310906
2  23:42:31    Ali  PIAIC310907
3  23:42:31   Ahad  PIAIC310908

https://docs.python.org/3/library/re.html