In [1]:
print("Fahad")

Fahad


In [3]:
!pip install nptyping beartype --upgrade --force

  Using cached nptyping-2.5.0-py3-none-any.whl.metadata (7.6 kB)
  Using cached beartype-0.17.2-py3-none-any.whl.metadata (30 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------- ------------------------- 20.5/61.0 kB 93.9 kB/s eta 0:00:01
     ------------- ------------------------- 20.5/61.0 kB 93.9 kB/s eta 0:00:01
     ------------- ------------------------- 20.5/61.0 kB 93.9 kB/s eta 0:00:01
     ------------- ------------------------- 20.5/61.0 kB 93.9 kB/s eta 0:00:01
     ------------------- ------------------- 30.7/61.0 kB 77.3 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 114.1 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 130.3 kB/s eta 0:00:00
Using cached nptyping-2.5.0-py3-none-any.whl (37 kB)
Using cached beartype-0.17.2-py3-none-a

## Scalar value

In [15]:
import numpy as np

a: np.ndarray = np.array(1000) # OBJECT TO STORE

display(a) #print(a)

display(a.shape) #print the shape of the object --> ZERO DIMENSION = NO SHAPE

display(a.dtype) #print the dtype of the object

display(type(a)) #print the type of the object 

display(a.ndim) #print the number of dimensions

display(a.size) #print the size of dimensions

display(a.itemsize) #print the item size of the object

array(1000)

()

dtype('int32')

numpy.ndarray

0

1

4

## Vector type

In [16]:
import numpy as np

a: np.ndarray = np.array([1,2,3,4]) # OBJECT TO STORE ([1,2,3,4]) = VECTOR TYPE

display(f" object{a}") #print(a)

display(f"object shape {a.shape}") #print the shape of the object --> ZERO DIMENSION = NO SHAPE

display(f" object type{a.dtype}") #print the dtype of the object

display(f"opject type with global function {type(a)}") #print the type of the object 

display(f"Number of dimensions {a.ndim}") #print the number of dimensions -> Vector data type dimension is = 1

display(f"Number of total items {a.size}") #print the size of dimensions

display(a.itemsize) #print the item size of the object

' object[1 2 3 4]'

'object shape (4,)'

' object typeint32'

"opject type with global function <class 'numpy.ndarray'>"

'Number of dimensions 1'

'Number of total items 4'

4

## Matrix

In [11]:
import numpy as np

data = [[0,1,2,3],
        [4,5,6,7],
        [8,9,10,11]]

a: np.ndarray = np.array(data) # OBJECT TO STORE ([1,2,3,4]) = VECTOR TYPE

display(f" object{a}") #print(a)

display(f"object shape {a.shape}") #print the shape of the object --> ZERO DIMENSION = NO SHAPE

display(f" object type{a.dtype}") #print the dtype of the object

display(f"opject type with global function {type(a)}") #print the type of the object 

display(f"Number of dimensions {a.ndim}") #print the number of dimensions -> Vector data type dimension is = 1

display(f"Number of total items {a.size}") #print the size of dimensions

display(a.itemsize) #print the item size of the object

' object[[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]'

'object shape (3, 4)'

' object typeint32'

"opject type with global function <class 'numpy.ndarray'>"

'Number of dimensions 2'

'Number of total items 12'

4

## Numpy with NDarray typing support

In [4]:
from nptyping import NDArray, Shape,  UInt64
from typing import Any

data : NDArray[Shape["10"], Any] = np.arange(1,11)

print(data)
print(data + 5) # addition operation

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]


In [15]:
%%time # for time measurement

data : NDArray[Shape["10"], Any] = np.arange(1,1000000)
data + 5

CPU times: total: 0 ns
Wall time: 5.8 ms


array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [19]:
%%time 
data : list[int] = list(range(1,1000000))

[i + 5 for i in data]

CPU times: total: 15.6 ms
Wall time: 117 ms


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


## Numpy advanced operations vs list operations

In [25]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11]) #



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


In [32]:
ndata: NDArray[Shape["20"], Any] = np.arange(1,21)
print(ndata)

print(ndata[5:11])

ndata[5:11] = 1000 # Changes the data

print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


## Numpy 1D functions

In [12]:
from nptyping import Bool

state_bank : NDArray[Shape["10"], Any] = np.array([1,7,8,10])

select: NDArray[Shape["10"], Bool] = np.array([True,False,False,True])

state_bank[select] # Passing select in the state_bank array will display the TRUE values as per index

array([ 1, 10])

In [13]:
state_bank : NDArray[Shape["10"], Any] = np.array([1,7,8,10])

state_bank % 2 == 0

array([False, False,  True,  True])

In [14]:
state_bank : NDArray[Shape["10"], Any] = np.array([1,7,8,10])

state_bank[state_bank % 2 == 0] # Where logic becomes true, it will display the number of TRUE values as per index


array([ 8, 10])

In [15]:
state_bank : NDArray[Shape["10"], Any] = np.array([1,7,8,10])

ubl_bank : NDArray[Shape["100"], Any] = np.random.randint(0,100,20)

display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([21, 28, 30, 26, 10, 29, 40,  9, 70, 69, 98, 95, 88, 47, 94, 14, 96,
       44, 31, 31])

In [16]:
display(state_bank)
display(ubl_bank)

np.in1d(state_bank,ubl_bank) #returns boolean 

array([ 1,  7,  8, 10])

array([21, 28, 30, 26, 10, 29, 40,  9, 70, 69, 98, 95, 88, 47, 94, 14, 96,
       44, 31, 31])

array([False, False, False,  True])

In [17]:
display(state_bank)
display(ubl_bank)

#       4items   search in 20 items 
state_bank[np.in1d(state_bank,ubl_bank)] # INTERSEC function will do the same thing in short --> see below



array([ 1,  7,  8, 10])

array([21, 28, 30, 26, 10, 29, 40,  9, 70, 69, 98, 95, 88, 47, 94, 14, 96,
       44, 31, 31])

array([10])

In [18]:
np.intersect1d(state_bank,ubl_bank)

array([10])

In [8]:
import numpy as np
from nptyping import NDArray, Shape,  UInt64
from typing import Any

ubl_bank : NDArray[Shape["100"], Any] = np.random.randint(1,100,20)

np.where(ubl_bank % 2 == 0)

(array([ 0,  2,  7,  8,  9, 10, 11, 13, 14, 15, 17, 19], dtype=int64),)

In [10]:
import numpy as np
from nptyping import NDArray, Shape,  UInt64
from typing import Any

ubl_bank: NDArray[Shape["100"], Any] = np.random.randint(1,100,10)
display(ubl_bank)

array([69, 96, 95, 99, 58, 68, 86, 19, 47,  5])

In [20]:
x : NDArray[Shape["10"], Any] = np.array([6,3,4,5,7])
y : NDArray[Shape["10"], Any] = np.array([1,3,2,5,100])

display(x)
display(y)

np.where(x > y, x, y)

array([6, 3, 4, 5, 7])

array([  1,   3,   2,   5, 100])

array([  6,   3,   4,   5, 100])

## Numpy Array

In [27]:
a : NDArray[Shape["*,*"], Any] = np.array([[1,2,3],# instead of size we can use *
                                                        [4,5,6]])
print(a)

a : NDArray[Shape["Size,Size"], Any] = np.array([[1,2],
                                                        [4,5]])
print(a)

a : NDArray[Shape["Size,Size"], Any] = np.array([["A"],
                                                        ["B"]])
# print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [28]:
np.who()

Name            Shape            Bytes            Type

_               5                20               int32
__              5                20               int32
___             5                20               int32
ubl_bank        10               40               int32
x               5                20               int32
y               5                20               int32
_17             5                20               int32
_18 (___)       5                20               int32
_19 (__)        5                20               int32
_20 (_)         5                20               int32
a               2 x 1            8                str32

Upper bound on total bytes  =       168


## Create any dimension array


In [30]:
a : NDArray[Shape["Size"], Any] = np.arange(1,5)
print(a)

a : NDArray[Shape["Size"], Any] = np.arange(1,10)
print(a)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [40]:
a : NDArray[Shape["Size, Size"], Any] = np.arange(3*3).reshape(3,3)
print(a)

a : NDArray[Shape["Size"], Any] = np.arange(5*3).reshape(5,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [42]:
a : NDArray[Shape["Size, Size, Size"], Any] = np.arange(2*3*3).reshape(2,3,3)
print(a)

print('========')
a : NDArray[Shape["Size, Size, Size"], Any] = np.arange(5*3*3).reshape(5,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]]]


In [43]:
a : NDArray[Shape["Size, Size, Size"], Any] = np.arange(5*2*2).reshape(5,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [44]:
a : NDArray[Shape["Size, Size, Size"], Any] = np.arange(5*2*2).reshape(5,2,2)
a[::2, ::, ::]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]]])

In [45]:
a : NDArray[Shape["Size, Size, Size"], Any] = np.arange(5*2*2).reshape(5,2,2)
a[a%2==0]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [50]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [52]:
np.ones_like(a) #ones_like will copy properties of the input array above but it will add 1 in all the elements


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [58]:
a : NDArray[Shape["Size, Size, Size"], Any] = np.arange(5*2*2).reshape(5,2,2)
print(a)

print('========')

a[[0,-1],::,::] #slicing took array's first and last picture

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [69]:
ndata: NDArray[Shape["20"], Any] = np.arange(1,21)
print(ndata)

print(ndata.min())
print(ndata.max())
print(ndata.sum())
print(ndata.mean())
print(ndata.std())
print(ndata.argmax()) #index number of maximum value
print(ndata.argmin()) #index number of minimum value

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
210
10.5
5.766281297335398
19
0
